### ISSUE TITLE
Permissions on start Jupyter

### ISSUE THREAD

**Issue by leapleys** [joelwking/devnet-sdk#3]
shell script doesn't copy as an exicutble and therefore errors on container build:

```shell
Running the postAttachCommand from devcontainer.json...

[88554 ms] Start: Run in container: /workspaces/devnet-sdk/start_jupyter.sh
[89370 ms] [15:07:44] [::ffff:127.0.0.1][d05ce44b][ExtensionHostConnection] New connection established.
[89456 ms] [15:07:44] [::ffff:127.0.0.1][d05ce44b][ExtensionHostConnection] <252> Launched Extension Host Process.
OCI runtime exec failed: exec failed: container_linux.go:380: starting container
 process caused: exec: "/workspaces/devnet-sdk/start_jupyter.sh": permission den
ied: unknown
[91013 ms] Error: Command failed: /workspaces/devnet-sdk/start_jupyter.sh
        at ag (c:\Users\leapleys\.vscode\extensions\ms-vscode-remote.remote-containers-0.183.0\dist\extension\extension.js:169:15)
        at async _V (c:\Users\leapleys\.vscode\extensions\ms-vscode-remote.remote-containers-0.183.0\dist\extension\extension.js:163:2880)
        at async c:\Users\leapleys\.vscode\extensions\ms-vscode-remote.remote-containers-0.183.0\dist\extension\extension.js:145:7815
[99162 ms] [15:07:54] Extracted extension to /root/.vscode-server/extensions/.d9ed4a90-9a15-4b9b-9aca-6e94dd10786e: ms-toolsai.jupyter
```

Showing file not executable
```shell
(jupyter) root@c902e6cc0623:/workspaces/devnet-sdk# ls -l
-rw-r--r-- 1 root root   362 Jun 23 21:57 start_jupyter.sh
```

Potential Fix
```shell
(jupyter) root@c902e6cc0623:/workspaces/devnet-sdk# chmod u+x start_jupyter.sh 
(jupyter) root@c902e6cc0623:/workspaces/devnet-sdk# ls -ls
 4 -rwxr--r-- 1 root root   362 Jun 23 21:57 start_jupyter.sh
```

**Comment by leapleys** [comment]
It appears as though you changed the "start_juputer.sh" file to all levels executable, but now bash is stating it can't find the file or it doesn't exist. 
 
Error upon executing the container
```shell
Running the postAttachCommand from devcontainer.json...

[71438 ms] Start: Run in container: /workspaces/devnet-sdk/start_jupyter.sh
/usr/bin/env: ‘bash\r’: No such file or directory
[73597 ms] Error: Command failed: /workspaces/devnet-sdk/start_jupyter.sh
        at ag (c:\Users\leapleys\.vscode\extensions\ms-vscode-remote.remote-containers-0.183.0\dist\extension\extension.js:169:15)
        at async _V (c:\Users\leapleys\.vscode\extensions\ms-vscode-remote.remote-containers-0.183.0\dist\extension\extension.js:163:2880)
        at async c:\Users\leapleys\.vscode\extensions\ms-vscode-remote.remote-containers-0.183.0\dist\extension\extension.js:145:7815
[75945 ms] [18:33:04] Extracted extension to /root/.vscode-server/extensions/.7e19c0ea-8ad5-4987-8f86-648a562aae72: ms-toolsai.jupyter
```

File prperties and execution error
```shell
(jupyter) root@9999c4210eea:/workspaces/devnet-sdk# ls -salt start_jupyter.sh 
0 -rwxrwxrwx 1 root root 374 Jun 23 21:24 start_jupyter.sh
(jupyter) root@9999c4210eea:/workspaces/devnet-sdk# ./start_jupyter.sh /usr/bin/env: ‘bash\r’: No such file or directory
(jupyter) root@9999c4210eea:/workspaces/devnet-sdk# 
```

**Comment by joelwking** [comment]
I corrected the file permission issue. Here are the steps I used to make the `start_jupyter.sh` maintain it's file permissions.

```shell
git update-index --chmod=+x start_jupyter.sh
git ls-files --stage
git commit -m 'updated file permissions for execute'
git push origin master
```

To test the change, I cloned from the remote to a `/tmp/` directory and started VS Code.

```shell
cd /tmp
git clone https://github.com/joelwking/devnet-sdk.git
cd devnet-sdk
ls -salt
```
The file has maintained the execute permission. Start VS Code.

```shell
code .
```

Let me know if you see any issues.

Joel

**Comment by leapleys** [comment]
Although the file is an executable it is still erroring out.  I deleted my clone, and downloaded a new clone to make sure it wasn't just on my version.

Log output from Devcontainer 
```shell
Running the postAttachCommand from devcontainer.json...

[20655 ms] Start: Run in container: /workspaces/devnet-sdk/start_jupyter.sh
[30379 ms] [14:54:26] [::ffff:127.0.0.1][00aec1dd][ExtensionHostConnection] New connection established.
[30381 ms] [14:54:26] [::ffff:127.0.0.1][00aec1dd][ExtensionHostConnection] <238> Launched Extension Host Process.
/usr/bin/env: ‘bash\r’: No such file or directory
[38539 ms] Error: Command failed: /workspaces/devnet-sdk/start_jupyter.sh
        at ag (c:\Users\leapleys\.vscode\extensions\ms-vscode-remote.remote-containers-0.183.0\dist\extension\extension.js:169:15)
        at async _V (c:\Users\leapleys\.vscode\extensions\ms-vscode-remote.remote-containers-0.183.0\dist\extension\extension.js:163:2880)
        at async c:\Users\leapleys\.vscode\extensions\ms-vscode-remote.remote-containers-0.183.0\dist\extension\extension.js:145:7815
```

File attributes and shell execution failure
```shell
(jupyter) root@9999c4210eea:/workspaces/devnet-sdk# ls -salt start_jupyter.sh 
0 -rwxrwxrwx 1 root root 374 Jun 25 14:50 start_jupyter.sh
(jupyter) root@9999c4210eea:/workspaces/devnet-sdk# ./start_jupyter.sh 
/usr/bin/env: ‘bash\r’: No such file or directory
(jupyter) root@9999c4210eea:/workspaces/devnet-sdk# 
```

**Comment by joelwking** [comment]
Are you running on macOS or Windows10? From your output, it looks like there is a `\r` in the Shebang line and `env` can't find `bash`.

I suspect if you do the following:
```shell
(jupyter) root@9dd5202cd600:/workspaces/devnet-sdk# /usr/bin/env bash
root@9dd5202cd600:/workspaces/devnet-sdk# exit
exit
(jupyter) root@9dd5202cd600:/workspaces/devnet-sdk# 
```
It will work?

When I run the following, it works OKAY.
```shell
(jupyter) root@9dd5202cd600:/workspaces/devnet-sdk# ./start_jupyter.sh
you are executing in (jupyter)
[I 20:25:09.525 NotebookApp] Serving notebooks from local directory: /workspaces/devnet-sdk
[I 20:25:09.525 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 20:25:09.525 NotebookApp] http://9dd5202cd600:8888/?token=345c1e02b4b956afb665ccddfc999591e2bf4eee7a059842
[I 20:25:09.525 NotebookApp]  or http://127.0.0.1:8888/?token=345c1e02b4b956afb665ccddfc999591e2bf4eee7a059842
[I 20:25:09.525 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:25:09.536 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/nbserver-1083-open.html
    Or copy and paste one of these URLs:
        http://9dd5202cd600:8888/?token=345c1e02b4b956afb665ccddfc999591e2bf4eee7a059842
     or http://127.0.0.1:8888/?token=345c1e02b4b956afb665ccddfc999591e2bf4eee7a059842
```
I'm thinking it might be an dos2unix / unix2dos issue: https://en.wikipedia.org/wiki/Unix2dos

**Comment by leapleys** [comment]
I'm on windows, but isn't the path \ bash within the container?

Thanx
Steve

**Comment by joelwking** [comment]
Try opening a terminal window in VS Code and running the commands I specified in your terminal window. I would like to see if you get the same results as when it runs in the `PostAttachCommand` directive in VS Code.

**Comment by leapleys** [comment]
Joel,

I executed the following in a VSC Terminal (bash) and resulted in no differences.
Like you said it seems like bash isn’t in the env, but it was working before on the first iteration because 
all I did was ```chmod +x start_jupyter.sh``` and then ```./start_jupyter.sh``` and it worked.  Why would the env have changed

```code 
git update-index --chmod=+x start_jupyter.sh
git ls-files --stage
git commit -m 'updated file permissions for execute'
git push origin master
```

**Comment by joelwking** [comment]
I am installing and testing on my personal Windows 10 computer to test.

I received the same error you are reporting:

```shell
Running the postCreateCommand from devcontainer.json...

[278027 ms] Start: Run in container: /bin/sh -c /bin/echo Hello from your new container
Hello from your new container

Running the postStartCommand from devcontainer.json...

[279299 ms] Start: Run in container: /bin/sh -c /bin/echo Welcome
Welcome

Running the postAttachCommand from devcontainer.json...

[280042 ms] Start: Run in container: /workspaces/devnet-sdk/start_jupyter.sh
/usr/bin/env: ‘bash\r’: No such file or directory


when running from terminal after container is started

(jupyter) root@7ebe7bc2a4e9:/workspaces/devnet-sdk# ./start_jupyter.sh 
/usr/bin/env: ‘bash\r’: No such file or directory
(jupyter) root@7ebe7bc2a4e9:/workspaces/devnet-sdk# 
```

**Comment by joelwking** [comment]
I made a few tweeks for this to run on both macOS and Windows10.   Look at the commits on 28th June under: https://github.com/joelwking/devnet-sdk/commits/master 

Let me know if this doesn't circumvent your issue. It did for me on Windows 10.

**Comment by leapleys** [comment]
> I made a few tweeks for this to run on both macOS and Windows10. Look at the commits on 28th June under: https://github.com/joelwking/devnet-sdk/commits/master
> 
> Let me know if this doesn't circumvent your issue. It did for me on Windows 10.

All goo here, Thanks

**Comment by leapleys** [comment]
Working now, Thanx

**Comment by joelwking** [comment]
Closing issue.
